### ISSUE TITLE
Not sure what version of this code is actually installed in HEAD Ska flight

### ISSUE THREAD

**Issue by jeanconn** [sot/hopper#7]

**Comment by taldcroft** [comment]
Can you give the backstory to this issue? What did you check and what made you confused?

**Comment by jeanconn** [comment]
I tried to check out flight hopper.  I had a few minutes and was curious
about low-impact changes to do aimpoint checks (as I figure I think
differently from you and complimentary strategies are sometimes
interesting).

Anyway, hopper seems to installed at "version 0.1" but I can't find a tag
or release for it.  Master seems to have WIP.


​

**Comment by taldcroft** [comment]
Hmm.  I'm working on the starcheck / hopper updates now.

**Comment by jeanconn** [comment]
I figured you would be.  Are you working from master?  And if so, are you
going to run with the aca checks you'd started?

**Comment by taldcroft** [comment]
I'll figure something out.

**Comment by jeanconn** [comment]
Understood.  I experimented with some parse_cm.or_list changes for fun last
night if you want them.​

**Comment by taldcroft** [comment]
The installed version matches https://github.com/sot/hopper/tree/6d97b4e04b5b.  The update I've made so far on master will apply cleanly at that point, so for the moment plan A is to make a new 0.1.x branch and develop there.

**Comment by jeanconn** [comment]
Closed by creation of [starcheck](https://github.com/sot/hopper/tree/starcheck) branch.
